# Rustfmt configuration for Silk Spool
edition = "2021"
max_width = 100
tab_spaces = 2
newline_style = "Unix"
use_small_heuristics = "Default"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
normalize_comments = true
normalize_doc_attributes = true
format_code_in_doc_comments = true
format_generated_files = false
